version: '3'

services:
  model-categorizer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CACHE_EXPIRATION=60
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./data:/app/data 