// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: models/proto/models.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model represents a single LLM model
type Model struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContextSize  int32                  `protobuf:"varint,3,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	MaxTokens    int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Provider     string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	DisplayName  string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description  string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CostPerToken float64                `protobuf:"fixed64,8,opt,name=cost_per_token,json=costPerToken,proto3" json:"cost_per_token,omitempty"`
	Capabilities []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Classification fields
	Family         string `protobuf:"bytes,10,opt,name=family,proto3" json:"family,omitempty"`
	Type           string `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Series         string `protobuf:"bytes,12,opt,name=series,proto3" json:"series,omitempty"`
	Variant        string `protobuf:"bytes,13,opt,name=variant,proto3" json:"variant,omitempty"`
	IsDefault      bool   `protobuf:"varint,14,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	IsMultimodal   bool   `protobuf:"varint,15,opt,name=is_multimodal,json=isMultimodal,proto3" json:"is_multimodal,omitempty"`
	IsExperimental bool   `protobuf:"varint,16,opt,name=is_experimental,json=isExperimental,proto3" json:"is_experimental,omitempty"`
	Version        string `protobuf:"bytes,17,opt,name=version,proto3" json:"version,omitempty"`
	// Additional metadata as string key-value pairs
	Metadata      map[string]string `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_models_proto_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_models_proto_models_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *Model) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *Model) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Model) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Model) GetCostPerToken() float64 {
	if x != nil {
		return x.CostPerToken
	}
	return 0
}

func (x *Model) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Model) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *Model) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Model) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Model) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *Model) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Model) GetIsMultimodal() bool {
	if x != nil {
		return x.IsMultimodal
	}
	return false
}

func (x *Model) GetIsExperimental() bool {
	if x != nil {
		return x.IsExperimental
	}
	return false
}

func (x *Model) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Model) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// LoadedModelList represents a list of models to be classified
type LoadedModelList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Models          []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	DefaultProvider string                 `protobuf:"bytes,2,opt,name=default_provider,json=defaultProvider,proto3" json:"default_provider,omitempty"`
	DefaultModel    string                 `protobuf:"bytes,3,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoadedModelList) Reset() {
	*x = LoadedModelList{}
	mi := &file_models_proto_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadedModelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadedModelList) ProtoMessage() {}

func (x *LoadedModelList) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadedModelList.ProtoReflect.Descriptor instead.
func (*LoadedModelList) Descriptor() ([]byte, []int) {
	return file_models_proto_models_proto_rawDescGZIP(), []int{1}
}

func (x *LoadedModelList) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *LoadedModelList) GetDefaultProvider() string {
	if x != nil {
		return x.DefaultProvider
	}
	return ""
}

func (x *LoadedModelList) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

// ClassificationProperty represents a property by which models can be classified
type ClassificationProperty struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PossibleValues []string               `protobuf:"bytes,4,rep,name=possible_values,json=possibleValues,proto3" json:"possible_values,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClassificationProperty) Reset() {
	*x = ClassificationProperty{}
	mi := &file_models_proto_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationProperty) ProtoMessage() {}

func (x *ClassificationProperty) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationProperty.ProtoReflect.Descriptor instead.
func (*ClassificationProperty) Descriptor() ([]byte, []int) {
	return file_models_proto_models_proto_rawDescGZIP(), []int{2}
}

func (x *ClassificationProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassificationProperty) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ClassificationProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClassificationProperty) GetPossibleValues() []string {
	if x != nil {
		return x.PossibleValues
	}
	return nil
}

// ClassifiedModelGroup represents a group of models classified by a property
type ClassifiedModelGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyName  string                 `protobuf:"bytes,1,opt,name=property_name,json=propertyName,proto3" json:"property_name,omitempty"`
	PropertyValue string                 `protobuf:"bytes,2,opt,name=property_value,json=propertyValue,proto3" json:"property_value,omitempty"`
	Models        []*Model               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifiedModelGroup) Reset() {
	*x = ClassifiedModelGroup{}
	mi := &file_models_proto_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifiedModelGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedModelGroup) ProtoMessage() {}

func (x *ClassifiedModelGroup) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedModelGroup.ProtoReflect.Descriptor instead.
func (*ClassifiedModelGroup) Descriptor() ([]byte, []int) {
	return file_models_proto_models_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifiedModelGroup) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

func (x *ClassifiedModelGroup) GetPropertyValue() string {
	if x != nil {
		return x.PropertyValue
	}
	return ""
}

func (x *ClassifiedModelGroup) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

// ClassificationCriteria defines how models should be classified
type ClassificationCriteria struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Properties          []string               `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	IncludeExperimental bool                   `protobuf:"varint,2,opt,name=include_experimental,json=includeExperimental,proto3" json:"include_experimental,omitempty"`
	IncludeDeprecated   bool                   `protobuf:"varint,3,opt,name=include_deprecated,json=includeDeprecated,proto3" json:"include_deprecated,omitempty"`
	MinContextSize      int32                  `protobuf:"varint,4,opt,name=min_context_size,json=minContextSize,proto3" json:"min_context_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClassificationCriteria) Reset() {
	*x = ClassificationCriteria{}
	mi := &file_models_proto_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationCriteria) ProtoMessage() {}

func (x *ClassificationCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationCriteria.ProtoReflect.Descriptor instead.
func (*ClassificationCriteria) Descriptor() ([]byte, []int) {
	return file_models_proto_models_proto_rawDescGZIP(), []int{4}
}

func (x *ClassificationCriteria) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ClassificationCriteria) GetIncludeExperimental() bool {
	if x != nil {
		return x.IncludeExperimental
	}
	return false
}

func (x *ClassificationCriteria) GetIncludeDeprecated() bool {
	if x != nil {
		return x.IncludeDeprecated
	}
	return false
}

func (x *ClassificationCriteria) GetMinContextSize() int32 {
	if x != nil {
		return x.MinContextSize
	}
	return 0
}

// ClassifiedModelResponse represents the response from the classification server
type ClassifiedModelResponse struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	ClassifiedGroups    []*ClassifiedModelGroup   `protobuf:"bytes,1,rep,name=classified_groups,json=classifiedGroups,proto3" json:"classified_groups,omitempty"`
	AvailableProperties []*ClassificationProperty `protobuf:"bytes,2,rep,name=available_properties,json=availableProperties,proto3" json:"available_properties,omitempty"`
	ErrorMessage        string                    `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClassifiedModelResponse) Reset() {
	*x = ClassifiedModelResponse{}
	mi := &file_models_proto_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifiedModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedModelResponse) ProtoMessage() {}

func (x *ClassifiedModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedModelResponse.ProtoReflect.Descriptor instead.
func (*ClassifiedModelResponse) Descriptor() ([]byte, []int) {
	return file_models_proto_models_proto_rawDescGZIP(), []int{5}
}

func (x *ClassifiedModelResponse) GetClassifiedGroups() []*ClassifiedModelGroup {
	if x != nil {
		return x.ClassifiedGroups
	}
	return nil
}

func (x *ClassifiedModelResponse) GetAvailableProperties() []*ClassificationProperty {
	if x != nil {
		return x.AvailableProperties
	}
	return nil
}

func (x *ClassifiedModelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_models_proto_models_proto protoreflect.FileDescriptor

const file_models_proto_models_proto_rawDesc = "" +
	"\n" +
	"\x19models/proto/models.proto\x12\fmodelservice\"\xf9\x04\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontext_size\x18\x03 \x01(\x05R\vcontextSize\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12$\n" +
	"\x0ecost_per_token\x18\b \x01(\x01R\fcostPerToken\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06family\x18\n" +
	" \x01(\tR\x06family\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12\x16\n" +
	"\x06series\x18\f \x01(\tR\x06series\x12\x18\n" +
	"\avariant\x18\r \x01(\tR\avariant\x12\x1d\n" +
	"\n" +
	"is_default\x18\x0e \x01(\bR\tisDefault\x12#\n" +
	"\ris_multimodal\x18\x0f \x01(\bR\fisMultimodal\x12'\n" +
	"\x0fis_experimental\x18\x10 \x01(\bR\x0eisExperimental\x12\x18\n" +
	"\aversion\x18\x11 \x01(\tR\aversion\x12=\n" +
	"\bmetadata\x18\x14 \x03(\v2!.modelservice.Model.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x0fLoadedModelList\x12+\n" +
	"\x06models\x18\x01 \x03(\v2\x13.modelservice.ModelR\x06models\x12)\n" +
	"\x10default_provider\x18\x02 \x01(\tR\x0fdefaultProvider\x12#\n" +
	"\rdefault_model\x18\x03 \x01(\tR\fdefaultModel\"\x9a\x01\n" +
	"\x16ClassificationProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fpossible_values\x18\x04 \x03(\tR\x0epossibleValues\"\x8f\x01\n" +
	"\x14ClassifiedModelGroup\x12#\n" +
	"\rproperty_name\x18\x01 \x01(\tR\fpropertyName\x12%\n" +
	"\x0eproperty_value\x18\x02 \x01(\tR\rpropertyValue\x12+\n" +
	"\x06models\x18\x03 \x03(\v2\x13.modelservice.ModelR\x06models\"\xc4\x01\n" +
	"\x16ClassificationCriteria\x12\x1e\n" +
	"\n" +
	"properties\x18\x01 \x03(\tR\n" +
	"properties\x121\n" +
	"\x14include_experimental\x18\x02 \x01(\bR\x13includeExperimental\x12-\n" +
	"\x12include_deprecated\x18\x03 \x01(\bR\x11includeDeprecated\x12(\n" +
	"\x10min_context_size\x18\x04 \x01(\x05R\x0eminContextSize\"\xe8\x01\n" +
	"\x17ClassifiedModelResponse\x12O\n" +
	"\x11classified_groups\x18\x01 \x03(\v2\".modelservice.ClassifiedModelGroupR\x10classifiedGroups\x12W\n" +
	"\x14available_properties\x18\x02 \x03(\v2$.modelservice.ClassificationPropertyR\x13availableProperties\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xe3\x01\n" +
	"\x1aModelClassificationService\x12X\n" +
	"\x0eClassifyModels\x12\x1d.modelservice.LoadedModelList\x1a%.modelservice.ClassifiedModelResponse\"\x00\x12k\n" +
	"\x1aClassifyModelsWithCriteria\x12$.modelservice.ClassificationCriteria\x1a%.modelservice.ClassifiedModelResponse\"\x00B4Z2github.com/chat-api/model-categorizer/models/protob\x06proto3"

var (
	file_models_proto_models_proto_rawDescOnce sync.Once
	file_models_proto_models_proto_rawDescData []byte
)

func file_models_proto_models_proto_rawDescGZIP() []byte {
	file_models_proto_models_proto_rawDescOnce.Do(func() {
		file_models_proto_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_proto_models_proto_rawDesc), len(file_models_proto_models_proto_rawDesc)))
	})
	return file_models_proto_models_proto_rawDescData
}

var file_models_proto_models_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_proto_models_proto_goTypes = []any{
	(*Model)(nil),                   // 0: modelservice.Model
	(*LoadedModelList)(nil),         // 1: modelservice.LoadedModelList
	(*ClassificationProperty)(nil),  // 2: modelservice.ClassificationProperty
	(*ClassifiedModelGroup)(nil),    // 3: modelservice.ClassifiedModelGroup
	(*ClassificationCriteria)(nil),  // 4: modelservice.ClassificationCriteria
	(*ClassifiedModelResponse)(nil), // 5: modelservice.ClassifiedModelResponse
	nil,                             // 6: modelservice.Model.MetadataEntry
}
var file_models_proto_models_proto_depIdxs = []int32{
	6, // 0: modelservice.Model.metadata:type_name -> modelservice.Model.MetadataEntry
	0, // 1: modelservice.LoadedModelList.models:type_name -> modelservice.Model
	0, // 2: modelservice.ClassifiedModelGroup.models:type_name -> modelservice.Model
	3, // 3: modelservice.ClassifiedModelResponse.classified_groups:type_name -> modelservice.ClassifiedModelGroup
	2, // 4: modelservice.ClassifiedModelResponse.available_properties:type_name -> modelservice.ClassificationProperty
	1, // 5: modelservice.ModelClassificationService.ClassifyModels:input_type -> modelservice.LoadedModelList
	4, // 6: modelservice.ModelClassificationService.ClassifyModelsWithCriteria:input_type -> modelservice.ClassificationCriteria
	5, // 7: modelservice.ModelClassificationService.ClassifyModels:output_type -> modelservice.ClassifiedModelResponse
	5, // 8: modelservice.ModelClassificationService.ClassifyModelsWithCriteria:output_type -> modelservice.ClassifiedModelResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_models_proto_models_proto_init() }
func file_models_proto_models_proto_init() {
	if File_models_proto_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_proto_models_proto_rawDesc), len(file_models_proto_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_proto_models_proto_goTypes,
		DependencyIndexes: file_models_proto_models_proto_depIdxs,
		MessageInfos:      file_models_proto_models_proto_msgTypes,
	}.Build()
	File_models_proto_models_proto = out.File
	file_models_proto_models_proto_goTypes = nil
	file_models_proto_models_proto_depIdxs = nil
}
